"""Allowlisted login-shell environment snapshot generation."""

from __future__ import annotations

import datetime as dt
import os
import subprocess

from .context import (
    ENVIRONMENT_CACHE,
    ROOT,
    elisp_string,
    is_windows,
    log,
    which,
    write_text_if_changed,
)

# Never persist arbitrary variables: login shells commonly contain secrets.
ENVIRONMENT_VARIABLES = {
    "BUNDLE_PATH",
    "CARGO_HOME",
    "C_INCLUDE_PATH",
    "CPLUS_INCLUDE_PATH",
    "CPATH",
    "GEM_HOME",
    "GOPATH",
    "GOROOT",
    "INFOPATH",
    "JAVA_HOME",
    "LANG",
    "LC_ALL",
    "LC_CTYPE",
    "LIBRARY_PATH",
    "MANPATH",
    "NVM_DIR",
    "PATH",
    "PKG_CONFIG_PATH",
    "RUSTUP_HOME",
    "SSH_AUTH_SOCK",
    "TEXMFHOME",
    "VIRTUAL_ENV",
    "VOLTA_HOME",
}


def capture_login_environment() -> dict[str, str] | None:
    """Return a login-shell environment, falling back to current env on Windows."""
    if is_windows():
        return dict(os.environ)
    shell = os.environ.get("SHELL") or which("zsh") or which("bash")
    if not shell:
        log("找不到登录 shell", "ERROR")
        return None
    try:
        result = subprocess.run(
            [shell, "-l", "-c", "env -0"],
            cwd=ROOT,
            capture_output=True,
            check=False,
        )
    except OSError as error:
        log(f"无法启动登录 shell: {error}", "ERROR")
        return None
    if result.returncode != 0:
        log(f"登录 shell 返回 {result.returncode}", "ERROR")
        if result.stderr:
            print(result.stderr.decode(errors="replace").rstrip())
        return None

    environment: dict[str, str] = {}
    for item in result.stdout.split(b"\0"):
        if b"=" not in item:
            continue
        key, value = item.split(b"=", 1)
        environment[key.decode(errors="replace")] = value.decode(errors="replace")
    return environment


def generate_environment_cache() -> bool:
    """Persist a safe subset of the login-shell environment as Elisp."""
    environment = capture_login_environment()
    if environment is None:
        return False
    selected = {
        key: value
        for key, value in environment.items()
        if key in ENVIRONMENT_VARIABLES or key.startswith("LC_")
    }
    if not selected.get("PATH"):
        log("登录 shell 没有返回 PATH，拒绝写入环境快照", "ERROR")
        return False

    created_at = (
        dt.datetime.now(dt.timezone.utc)
        .astimezone()
        .isoformat(timespec="seconds")
    )
    lines = [
        ";;; environment.el --- generated shell environment -*- lexical-binding: t; -*-",
        ";; Auto-generated by update_emacs.py env. DO NOT EDIT.",
        f";; Generated: {created_at}",
        ";; Only allowlisted, non-secret variables are persisted.",
        "",
        "(dolist (entry",
        "         '(",
    ]
    for key, value in sorted(selected.items()):
        lines.append(
            f'           ("{elisp_string(key)}" . "{elisp_string(value)}")'
        )
    lines.extend([
        "           ))",
        "  (setenv (car entry) (cdr entry)))",
        "(let ((path (getenv \"PATH\")))",
        "  (when path",
        "    (setq exec-path",
        "          (append (parse-colon-path path)",
        "                  (when (boundp 'exec-directory) (list exec-directory))))))",
        "",
        "(provide 'environment)",
        ";;; environment.el ends here",
        "",
    ])
    ENVIRONMENT_CACHE.parent.mkdir(parents=True, exist_ok=True)
    changed = write_text_if_changed(ENVIRONMENT_CACHE, "\n".join(lines))
    try:
        ENVIRONMENT_CACHE.chmod(0o600)
    except OSError:
        pass
    state = "已生成" if changed else "未变化"
    log(
        f"{state} {ENVIRONMENT_CACHE.relative_to(ROOT)}"
        f"（{len(selected)} 个白名单变量）"
    )
    return True
