"""Platform-local idle feature plan generation."""

from __future__ import annotations

import re
import subprocess

from . import context
from .context import (
    IDLE_FEATURE_CACHE,
    ROOT,
    elisp_string,
    find_emacs,
    log,
    write_text_if_changed,
)

FEATURE_RE = re.compile(r"^[a-zA-Z0-9][a-zA-Z0-9_+-]*$")


def generate_idle_feature_cache() -> bool:
    """Generate a platform-local idle-load plan from observed requires."""
    emacs = find_emacs()
    if not emacs:
        log("未找到 emacs，无法生成 idle feature 缓存", "ERROR")
        return False

    generator = ROOT / "scripts" / "generate-idle-features.el"
    if not generator.is_file():
        log(f"缺少 idle feature 生成器: {generator}", "ERROR")
        return False
    try:
        result = subprocess.run(
            [emacs, "--batch", "-Q", "-l", str(generator)],
            cwd=ROOT,
            text=True,
            capture_output=True,
            check=False,
            timeout=180,
        )
    except (OSError, subprocess.TimeoutExpired) as error:
        log(f"idle feature 发现失败: {error}", "ERROR")
        return False
    if result.returncode != 0:
        log("idle feature 发现失败", "ERROR")
        if result.stdout.strip():
            print(result.stdout.strip())
        if result.stderr.strip():
            print(result.stderr.strip())
        return False

    system_type: str | None = None
    generated_emacs_version: str | None = None
    source_signature: str | None = None
    tasks: list[str] = []
    warnings: list[str] = []
    for line in result.stdout.splitlines():
        fields = line.split("\t")
        if len(fields) == 3 and fields[:2] == ["IDLE_META", "system-type"]:
            system_type = fields[2]
        elif len(fields) == 3 and fields[:2] == ["IDLE_META", "emacs-version"]:
            generated_emacs_version = fields[2]
        elif len(fields) == 3 and fields[:2] == ["IDLE_META", "source-signature"]:
            source_signature = fields[2]
        elif len(fields) == 2 and fields[0] == "IDLE_TASK":
            tasks.append(fields[1])
        elif len(fields) == 2 and fields[0] == "IDLE_WARNING":
            warnings.append(fields[1])

    if (
        not system_type
        or not generated_emacs_version
        or not source_signature
        or not re.fullmatch(r"[0-9a-f]{64}", source_signature)
        or not tasks
        or not FEATURE_RE.fullmatch(system_type)
        or any(not task.startswith("(") or not task.endswith(")") for task in tasks)
    ):
        log("idle feature 生成器返回了无效数据", "ERROR")
        if context.VERBOSE and result.stdout.strip():
            print(result.stdout.strip())
        return False

    lines = [
        ";;; idle-features.el --- generated idle-load plan -*- lexical-binding: t; -*-",
        ";; Auto-generated by update_emacs.py. DO NOT EDIT.",
        f";; Emacs {generated_emacs_version} on {system_type}.",
        "",
        f"(setq my/idle-loader-generated-system-type '{system_type}",
        "      my/idle-loader-generated-emacs-version",
        f'      "{elisp_string(generated_emacs_version)}"',
        "      my/idle-loader-generated-source-signature",
        f'      "{elisp_string(source_signature)}"',
        "      my/idle-loader-generated-plan",
        "      '(",
    ]
    lines.extend(f"        {task}" for task in tasks)
    lines.extend([
        "        ))",
        "",
        "(provide 'idle-features)",
        ";;; idle-features.el ends here",
        "",
    ])
    changed = write_text_if_changed(IDLE_FEATURE_CACHE, "\n".join(lines))
    state = "已生成" if changed else "未变化"
    log(
        f"{state} {IDLE_FEATURE_CACHE.relative_to(ROOT)}"
        f"（tasks={len(tasks)}, warnings={len(warnings)}, {system_type}）"
    )
    for warning in warnings:
        log(f"idle task 无法在 batch 中探测: {warning}", "WARN")
    if context.VERBOSE and result.stderr.strip():
        print(result.stderr.strip())
    return True
